name: Routine Scan

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:
    inputs:
      target_domain:
        description: 'Enter Target Domain'
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          pip install requests uro
          mkdir -p output && chmod -R 755 output

      - name: Execute PII Scan
        run: |
          echo "[+] Running PII scan..."
          chmod +x ./pii.sh

          if [ -n "${{ github.event.inputs.target_domain }}" ]; then
            ./pii.sh "${{ github.event.inputs.target_domain }}" > output/findings.txt
          else
            ./pii.sh > output/findings.txt
          fi

          if [ -s output/findings.txt ]; then
            echo "[+] Findings detected. Generating report..."
            {
              echo "Timestamp: $(date -u)"
              [ -n "${{ github.event.inputs.target_domain }}" ] && echo "Target: ${{ github.event.inputs.target_domain }}"
              echo "---"
              cat output/findings.txt
            } > output/report.txt
            
            curl -H "Content-Type: multipart/form-data" \
                 -F "file=@output/report.txt" \
                 ${{ secrets.SLACK_WEBHOOK_URL }}
            echo "[+] Report sent to Slack."
          else
            echo "[+] No findings detected. Skipping report generation."
          fi

      - name: Verify Output Directory
        run: |
          echo "Verifying output directory contents..."
          ls -l output/
          cat output/report.txt || echo "No report file found."

      - name: Upload Findings as Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: PII-Scan-Findings
          path: output/

      - name: Cleanup
        run: |
          echo "[+] Cleaning up output directory..."
          rm -rf output/
          echo "[+] Cleanup complete."

      - name: Notify Failure
        if: failure()
        run: |
          echo "❌ Workflow failed. Check logs for details."
          curl -X POST -H "Content-Type: application/json" \
               -d '{"text": "❌ Workflow failed. Check logs for details."}' \
               ${{ secrets.SLACK_WEBHOOK_URL }}
