name: Automated PII Scan

on:
  schedule:
    # Run every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Allow manual triggers
    inputs:
      domain:
        description: "Domain to scan"
        required: false

jobs:
  pii-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl file grep findutils coreutils
          curl -sSfL https://raw.githubusercontent.com/tomnomnom/uro/master/uro > /usr/local/bin/uro
          chmod +x /usr/local/bin/uro

      - name: Verify Dependencies
        run: |
          xargs --version
          curl --version
          file --version
          grep --version

      - name: Run pii.sh Script
        run: |
          DOMAIN=${{ github.event.inputs.domain || '' }}
          chmod +x pii.sh
          ./pii.sh "$DOMAIN"

      - name: Upload Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: pii-scan-results
          path: output
