name: Routine Scan

on:
  # schedule:
  #   - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      target_domain:
        description: 'Enter Target'
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup
        run: |
          pip install requests uro > /dev/null 2>&1
          sudo apt-get update > /dev/null 2>&1
          sudo apt-get install -y curl jq > /dev/null 2>&1
          mkdir -p output

      - name: Execute scan
        run: |
          chmod +x ./pii.sh
          if [ -n "${{ github.event.inputs.target_domain }}" ]; then
            ./pii.sh "${{ github.event.inputs.target_domain }}" > output/findings.txt 2>/dev/null
          else
            ./pii.sh > output/findings.txt 2>/dev/null
          fi
          
          if [ -s output/findings.txt ]; then
            {
              echo "Timestamp: $(date -u)"
              [ -n "${{ github.event.inputs.target_domain }}" ] && echo "Target: ${{ github.event.inputs.target_domain }}"
              echo "---"
              cat output/findings.txt
            } > output/report.txt
            
            curl -H "Content-Type: multipart/form-data" \
                 -F "file=@output/report.txt" \
                 ${{ secrets.DISCORD_WEBHOOK_URL }} > /dev/null 2>&1
          fi
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Cleanup
        run: rm -rf output/
