name: Routine Scan

on:
  # schedule:
  #   - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      target_domain:
        description: 'Enter Target'
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup
        run: |
          pip install requests uro > /dev/null 2>&1
          sudo apt-get update > /dev/null 2>&1
          sudo apt-get install -y curl jq > /dev/null 2>&1
          mkdir -p output

- name: Execute pii.sh Script
  run: |
    mkdir -p output
    chmod +x ./pii.sh
    if [ -n "${{ github.event.inputs.target_domain }}" ]; then
      ./pii.sh "${{ github.event.inputs.target_domain }}" > output/findings.txt
    else
      ./pii.sh > output/findings.txt
    fi

    if [ -s output/findings.txt ]; then
      {
        echo "Timestamp: $(date -u)"
        [ -n "${{ github.event.inputs.target_domain }}" ] && echo "Target: ${{ github.event.inputs.target_domain }}"
        echo "---"
        cat output/findings.txt
      } > output/report.txt
      
      curl -H "Content-Type: multipart/form-data" \
           -F "file=@output/report.txt" \
           ${{ secrets.SLACK_WEBHOOK_URL }}
    else
      echo "No findings detected."
    fi
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Cleanup
        run: rm -rf output/
