name: Routine Scan

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:
    inputs:
      target_domain:
        description: 'Enter Target Domain'
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          echo "[+] Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y curl jq
          pip install requests uro
          mkdir -p output
          echo "[+] Setup complete. Output directory created."

      - name: Execute PII Scan
        run: |
          echo "[+] Running PII scan..."
          chmod +x ./pii.sh

          # Execute the scan with or without target_domain
          if [ -n "${{ github.event.inputs.target_domain }}" ]; then
            ./pii.sh "${{ github.event.inputs.target_domain }}" > output/findings.txt
          else
            ./pii.sh > output/findings.txt
          fi

          # Check if findings exist and create a report
          if [ -s output/findings.txt ]; then
            echo "[+] Findings detected. Generating report..."
            {
              echo "Timestamp: $(date -u)"
              [ -n "${{ github.event.inputs.target_domain }}" ] && echo "Target: ${{ github.event.inputs.target_domain }}"
              echo "---"
              cat output/findings.txt
            } > output/report.txt
            
            # Send the report to Discord
            curl -H "Content-Type: multipart/form-data" \
                 -F "file=@output/report.txt" \
                 ${{ secrets.DISCORD_WEBHOOK_URL }}
            echo "[+] Report sent to Discord."
          else
            echo "[+] No findings detected. Skipping report generation."
          fi
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Cleanup
        run: |
          echo "[+] Cleaning up output directory..."
          rm -rf output/
          echo "[+] Cleanup complete."
