name: Hello

on:
  workflow_dispatch:
    inputs:
      sleep_duration_hours:
        description: 'Limit (max: 6hrs)'
        required: false
        default: '1'

jobs:
  Hey:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tmate Session
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate openssh-client
          
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          
          SSH_CMD=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          WEB_URL=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
          
          JSON_MSG=$(jq -n \
            --arg ssh "🔐 **SSH Access Details**" \
            --arg sshCmd "**SSH Command:** ||\`$SSH_CMD\`||" \
            --arg webUrl "**Web URL:** [view on web]($WEB_URL)" \
            --arg note "**Note:** _Session will remain active for ${{ github.event.inputs.sleep_duration_hours }} hour(s)_" \
            '{content: "\($ssh)\n\n\($sshCmd)\n\($webUrl)\n\n\($note)"}')
          curl -H "Content-Type: application/json" \
            -d "$JSON_MSG" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
      
      - name: Keep Alive
        run: |
          SLEEP_DURATION_SECONDS=$(( $(echo ${{ github.event.inputs.sleep_duration_hours }}) * 3600 ))
          sleep $SLEEP_DURATION_SECONDS
